SQL Interview Notes - Part 1
Question 1
Find students eligible for placement.
Tables Used
students
student_id	name	branch
exam_scores

|student_id|subject|score|

projects

|student_id|marks|

Business Requirement

A student is eligible if

At least one exam score >=90
At least one project marks >=85
Step 1

What is the output?

student_id

name

branch

Question:

Where are these columns?

Answer:

students

Therefore

FROM students
Step 2

How do we know whether the student scored >=90?

Question:

Which table contains score?

Answer

exam_scores

Need

student_id

because later we compare it with students table.

Subquery

SELECT student_id
FROM exam_scores
WHERE score>=90;

Output

S101

S105

S106

S109

Question

Why don't we select score?

Answer

Because IN compares

student_id

with

student_id

Both sides must have compatible values.

Step 3

Project condition

SELECT student_id
FROM projects
WHERE marks>=85;

Output

S101

S105

S106

S109
Step 4

Final Query

SELECT
    s.student_id,
    s.name,
    s.branch
FROM students s
WHERE s.student_id IN
(
    SELECT student_id
    FROM exam_scores
    WHERE score>=90
)
AND s.student_id IN
(
    SELECT student_id
    FROM projects
    WHERE marks>=85
);
Why IN?

Question

Why did we use IN?

Answer

Because the subquery returns

Multiple rows

Multiple student_ids

IN is specifically designed to compare one value against multiple values.

Follow-up Interview Questions
Q

Can this be solved using JOIN?

Answer

Yes.

SELECT DISTINCT
    s.student_id,
    s.name,
    s.branch
FROM students s
JOIN exam_scores e
ON s.student_id=e.student_id
JOIN projects p
ON s.student_id=p.student_id
WHERE e.score>=90
AND p.marks>=85;
Q

Why DISTINCT?

Answer

One student can have

Math

Physics

SQL

Three rows.

Without DISTINCT

same student appears multiple times.

Q

Can this be solved using EXISTS?

Answer

Yes.

Interviewers love EXISTS.

Question 2

Students scoring above class average.

Business Requirement

Find

Student Name

Student ID

Score

Subject

where

Student Score

>

Class Average
Step 1

Need

Student Name

Question

Which table?

students

Need score

Question

Which table?

exam_scores

Therefore

Need JOIN.

Step 2

Average score

Question

Where is average stored?

Answer

Nowhere.

Need to calculate.

SELECT AVG(score)
FROM exam_scores;

Suppose

Output

84.8
Step 3

Final Query

SELECT
    s.name,
    s.student_id,
    e.score,
    e.subject
FROM students s
JOIN exam_scores e
ON s.student_id=e.student_id
WHERE e.score>
(
    SELECT AVG(score)
    FROM exam_scores
);
Interview Question

Why Subquery?

Answer

Because

Average must first be calculated.

Then

each student's score

is compared against that value.

Can we use JOIN instead?

No.

JOIN combines tables.

Average is a calculated value.

Need Subquery

or

Window Function

Window Function Solution
SELECT *
FROM
(
SELECT *,
AVG(score) OVER() class_avg
FROM exam_scores
)t
WHERE score>class_avg;
Interview Question

Which is better?

Window Function

because

average is calculated once

while keeping row-level details.

Question 3

Placement using JOIN

Query

SELECT
s.name,
e.score,
p.marks
FROM students s
JOIN exam_scores e
ON s.student_id=e.student_id
JOIN projects p
ON s.student_id=p.student_id
WHERE e.score>=90
AND p.marks>=85;
Why JOIN?

Need columns from

students

exam_scores

projects

Therefore

Need three table join.

Interview Question

Why INNER JOIN?

Because

Need only matching students.

LEFT JOIN

would return students without exams.

Interview Question

Can duplicates occur?

Yes.

Example

Student has

Math

Physics

SQL

Project

One project

Result

3 rows

Need

DISTINCT

GROUP BY

depending on requirement.

Question 4

Total Score

Number of Exams

Subquery

SELECT
student_id,
SUM(score) total_score,
COUNT(*) no_of_attempts
FROM exam_scores
GROUP BY student_id;

Output

Student

Total Score

Exam Count

Temporary Table

student_id

total_score

no_of_attempts

Outer Query

SELECT
s.name,
s.branch,
total_stats.total_score,
total_stats.no_of_attempts
FROM
(
SELECT
student_id,
SUM(score) total_score,
COUNT(*) no_of_attempts
FROM exam_scores
GROUP BY student_id
) total_stats
JOIN students s
ON s.student_id=total_stats.student_id;

Interview Question

What is

total_stats

Answer

Derived Table.

Temporary table generated by Subquery.

Interview Question

Can this be written using CTE?

Yes.

WITH total_stats AS
(
SELECT
student_id,
SUM(score) total_score,
COUNT(*) no_of_attempts
FROM exam_scores
GROUP BY student_id
)

SELECT
s.name,
s.branch,
total_stats.total_score,
total_stats.no_of_attempts
FROM students s
JOIN total_stats
ON s.student_id=total_stats.student_id;
Very Important Interview Concepts
SQL Logical Order of Execution

This is asked very frequently.

FROM

JOIN

ON

WHERE

GROUP BY

HAVING

SELECT

DISTINCT

ORDER BY

LIMIT

Remember:

SQL is written in one order, but logically processed in another.

Alias
students s

Why?

Two reasons

Avoid ambiguity

student_id

exists in multiple tables

Improve readability

students.student_id

↓

s.student_id
Subquery Types

You should know these four:

Scalar Subquery
Returns one value.
Example: AVG(score).
Multi-row Subquery
Returns multiple rows.
Example: IN (SELECT student_id ...).
Correlated Subquery
Inner query depends on the outer query.
Example: Compare each student's score with the average score of their own branch.
Derived Table
Subquery in the FROM clause.
Behaves like a temporary table.
